# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    name: sync to Gitlab 
    runs-on: ubuntu-latest
    steps:
      - name: checkout MUST use version 1
        uses: actions/checkout@v1
      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@ssl-gitlab.csie.ntut.edu.tw:timchang1005/pvs-react.git
